### PR TITLE
FH uses CocoaPods 1.0.1

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by matzew** [comment]
@corinnekrych @jcesarmobile can this be merged ?

**Comment by corinnekrych** [comment]
once Travis is ok yes

**Comment by jcesarmobile** [comment]
Version.txt should be updated to 3.2.0
libPods-FH.a and libPods-FH-FHTests.a should be removed because they are 0.3x files that might cause problems.
testSyncClientListCollision test fails

**Comment by matzew** [comment]
Just ran this locally

```
pod install
```

was all ✅ 

next, I did ran `xctool`, like Travis does too:
```
xctool -workspace fh-ios-sdk.xcworkspace -scheme FH -sdk iphonesimulator build test
```

And this was also all ✅ 


Is this an issue w/ Travis ?

**Comment by jcesarmobile** [comment]
tried again and testSyncClientListCollision passed this time

**Comment by danielpassos** [comment]
@matzew I got the same problem of @travis-ci running: 
`xctool -workspace fh-ios-sdk.xcworkspace -scheme FH -sdk iphonesimulator build test`

```
Failures:

  0) -[FHTests testCloud500Response] (FHTests.xctest)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2016-09-13 13:55:34.779 xctest[9751:110291] *** Terminating app due to uncaught exception 'NocillaUnexpectedRequest', reason: 'An unexpected HTTP request was fired.

Use this snippet to stub the request:
stubRequest(@"POST", @"http://testing.feedhenry.com/api/v2/ag-push/rest/registry/device").
withHeaders(@{ @"Authorization": @"Basic dmFyaWFudElEOnZhcmlhbnRTZWNyZXQ=", @"Content-Length": @"62", @"Content-Type": @"application/json" }).
withBody(@"{\"deviceToken\":\"414141412d424242422d43434343\",\"alias\":\"ALIAS\"}");
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00821494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x00b94e02 objc_exception_throw + 50
	2   CoreFoundation                      0x008213bd +[NSException raise:format:] + 141
	3   FHTests                             0x0c1ce7f0 -[LSNocilla responseForRequest:] + 880
	4   FHTests                             0x0c1cd528 -[LSHTTPStubURLProtocol startLoading] + 168
	5   CFNetwork                           0x037c29b8 _ZN16CFURLProtocol_NS28_protocolInterface_startLoadEPK20_CFCachedURLResponse + 324
	6   CFNetwork                           0x038c4fe4 ___ZN19URLConnectionLoader27_private_ScheduleOriginLoadEPK12NSURLRequestPK20_CFCachedURLResponse_block_invoke_2 + 62
	7   CFNetwork                           0x0379c428 ___ZNK19URLConnectionLoader25withExistingProtocolAsyncEU13block_pointerFvP11URLProtocolE_block_invoke + 30
	8   libdispatch.dylib                   0x033ea6ed _dispatch_client_callout + 14
	9   libdispatch.dylib                   0x033cf218 _dispatch_block_invoke + 377
	10  libdispatch.dylib                   0x033e7f08 ___dispatch_block_create_block_invoke + 20
	11  CFNetwork                           0x0379c3fa _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
	12  CoreFoundation                      0x007041f9 CFArrayApplyFunction + 57
	13  CFNetwork                           0x0379c2f5 _ZN19RunloopBlockContext7performEv + 143
	14  CFNetwork                           0x0395c3da _ZThn16_N19RunloopBlockContext24multiplexerClientPerformEv + 20
	15  CFNetwork                           0x0379c1b2 _ZN17MultiplexerSource7performEv + 326
	16  CFNetwork                           0x0379bfca _ZN17MultiplexerSource8_performEPv + 76
	17  CoreFoundation                      0x00733e5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	18  CoreFoundation                      0x00729aeb __CFRunLoopDoSources0 + 523
	19  CoreFoundation                      0x00728f08 __CFRunLoopRun + 1032
	20  CoreFoundation                      0x00728846 CFRunLoopRunSpecific + 470
	21  CoreFoundation                      0x0072865b CFRunLoopRunInMode + 123
	22  CFNetwork                           0x03839036 +[NSURLConnection(Loader) _resourceLoadLoop:] + 472
	23  Foundation                          0x002c4eda -[NSThread main] + 76
	24  Foundation                          0x0037a2dc __NSThread__start__ + 1346
	25  libsystem_pthread.dylib             0x03713780 _pthread_body + 138
	26  libsystem_pthread.dylib             0x037136f6 _pthread_body + 0
	27  libsystem_pthread.dylib             0x03710f7a thread_start + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Child process terminated with signal 6: Abort trap

Test crashed while running.

CRASH REPORT: xctest_2016-09-13-135536_Daniels-MacBook-Air.crash

Process:               xctest [9751]
Path:                  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/usr/bin/xctest
Identifier:            xctest
Version:               10111
Code Type:             X86 (Native)
Parent Process:        simctl [9749]
Responsible:           iTerm2 [5064]
User ID:               501

Date/Time:             2016-09-13 13:55:34.869 -0300
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        36699524-4173-1920-A3D4-38E08FD28BFA


Time Awake Since Boot: 7600 seconds

System Integrity Protection: enabled

Crashed Thread:        5  com.apple.NSURLConnectionLoader

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NocillaUnexpectedRequest', reason: 'An unexpected HTTP request was fired.

Use this snippet to stub the request:
stubRequest(@"POST", @"http://testing.feedhenry.com/api/v2/ag-push/rest/registry/device").
withHeaders(@{ @"Authorization": @"Basic dmFyaWFudElEOnZhcmlhbnRTZWNyZXQ=", @"Content-Length": @"62", @"Content-Type": @"application/json" }).
withBody(@"{\"deviceToken\":\"414141412d424242422d43434343\",\"alias\":\"ALIAS\"}");
'
terminating with uncaught exception of type NSException
abort() called
CoreSimulator 209.19 - Device: iPhone 4s - Runtime: iOS 9.3 (13E230) - DeviceType: iPhone 4s

Application Specific Backtrace 1:
0   CoreFoundation                      0x00821494 __exceptionPreprocess + 180
1   libobjc.A.dylib                     0x00b94e02 objc_exception_throw + 50
2   CoreFoundation                      0x008213bd +[NSException raise:format:] + 141
3   FHTests                             0x0c1ce7f0 -[LSNocilla responseForRequest:] + 880
4   FHTests                             0x0c1cd528 -[LSHTTPStubURLProtocol startLoading] + 168
5   CFNetwork                           0x037c29b8 _ZN16CFURLProtocol_NS28_protocolInterface_startLoadEPK20_CFCachedURLResponse + 324
6   CFNetwork                           0x038c4fe4 ___ZN19URLConnectionLoader27_private_ScheduleOriginLoadEPK12NSURLRequestPK20_CFCachedURLResponse_block_invoke_2 + 62
7   CFNetwork                           0x0379c428 ___ZNK19URLConnectionLoader25withExistingProtocolAsyncEU13block_pointerFvP11URLProtocolE_block_invoke + 30
8   libdispatch.dylib                   0x033ea6ed _dispatch_client_callout + 14
9   libdispatch.dylib                   0x033cf218 _dispatch_block_invoke + 377
10  libdispatch.dylib                   0x033e7f08 ___dispatch_block_create_block_invoke + 20
11  CFNetwork                           0x0379c3fa _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
12  CoreFoundation                      0x007041f9 CFArrayApplyFunction + 57
13  CFNetwork                           0x0379c2f5 _ZN19RunloopBlockContext7performEv + 143
14  CFNetwork                           0x0395c3da _ZThn16_N19RunloopBlockContext24multiplexerClientPerformEv + 20
15  CFNetwork                           0x0379c1b2 _ZN17MultiplexerSource7performEv + 326
16  CFNetwork                           0x0379bfca _ZN17MultiplexerSource8_performEPv + 76
17  CoreFoundation                      0x00733e5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
18  CoreFoundation                      0x00729aeb __CFRunLoopDoSources0 + 523
19  CoreFoundation                      0x00728f08 __CFRunLoopRun + 1032
20  CoreFoundation                      0x00728846 CFRunLoopRunSpecific + 470
21  CoreFoundation                      0x0072865b CFRunLoopRunInMode + 123
22  CFNetwork                           0x03839036 +[NSURLConnection(Loader) _resourceLoadLoop:] + 472
23  Foundation                          0x002c4eda -[NSThread main] + 76
24  Foundation                          0x0037a2dc __NSThread__start__ + 1346
25  libsystem_pthread.dylib             0x03713780 _pthread_body + 138
26  libsystem_pthread.dylib             0x037136f6 _pthread_body + 0
27  libsystem_pthread.dylib             0x03710f7a thread_start + 34

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x037474d6 semaphore_wait_trap + 10
1   libdispatch.dylib             	0x033d5ab0 _dispatch_semaphore_wait_slow + 298
2   libdispatch.dylib             	0x033d597d dispatch_semaphore_wait + 37
3   libxpc.dylib                  	0x036d7c2f xpc_connection_send_message_with_reply_sync + 258
4   com.apple.MobileCoreServices  	0x03bd6256 _LSCopyVendorIdentifier + 106
5   com.apple.MobileCoreServices  	0x03be59e1 -[LSApplicationWorkspace deviceIdentifierForVendor] + 37
6   com.apple.UIKit               	0x014003e6 -[UIDevice identifierForVendor] + 66
7   com.feedhenry.FHTests         	0x0c1ef732 -[FHConfig vendorId] + 162 (FHConfig.m:101)
8   com.feedhenry.FHTests         	0x0c1ea57a +[FH getDefaultParams] + 1226 (FH.m:338)
9   com.feedhenry.FHTests         	0x0c1faa5a -[FHAct defaultParams] + 138 (FHAct.m:61)
10  com.feedhenry.FHTests         	0x0c22391f -[FHInitRequest init] + 255 (FHInitRequest.m:28)
11  com.feedhenry.FHTests         	0x0c1e66c0 +[FH initWithSuccess:AndFailure:] + 1008 (FH.m:64)
12  com.feedhenry.FHTests         	0x0c1a590f -[FHTests setUp] + 991 (FHTests.m:52)
13  com.apple.dt.XCTest           	0x00183de8 __24-[XCTestCase invokeTest]_block_invoke_3 + 32
14  com.apple.dt.XCTest           	0x00187bae -[XCTestCase startActivityWithTitle:block:] + 581
15  com.apple.dt.XCTest           	0x00183a06 __24-[XCTestCase invokeTest]_block_invoke_2 + 134
16  com.apple.dt.XCTest           	0x001bcdf9 -[XCTestContext performInScope:] + 229
17  com.apple.dt.XCTest           	0x00183973 -[XCTestCase invokeTest] + 177
18  com.apple.dt.XCTest           	0x001840d0 -[XCTestCase performTest:] + 519
19  otest-shim-ios.dylib          	0x00155ffa XCPerformTestWithSuppressedExpectedAssertionFailures + 542
20  otest-shim-ios.dylib          	0x001556f4 XCTestCase_performTest + 31
21  com.apple.dt.XCTest           	0x001aed4c -[XCTest runTest] + 308
22  com.apple.dt.XCTest           	0x001815e1 -[XCTestSuite performTest:] + 429
23  com.apple.dt.XCTest           	0x001aed4c -[XCTest runTest] + 308
24  com.apple.dt.XCTest           	0x001815e1 -[XCTestSuite performTest:] + 429
25  com.apple.dt.XCTest           	0x001aed4c -[XCTest runTest] + 308
26  com.apple.dt.XCTest           	0x001815e1 -[XCTestSuite performTest:] + 429
27  com.apple.dt.XCTest           	0x001aed4c -[XCTest runTest] + 308
28  com.apple.dt.XCTest           	0x001be650 ___XCTestMain_block_invoke.79 + 32
29  com.apple.dt.XCTest           	0x001911f9 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 767
30  com.apple.dt.XCTest           	0x001be522 _XCTestMain + 1089
31  xctest                        	0x000f3674 0xf2000 + 5748
32  libdyld.dylib                 	0x0340fa25 start + 1

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x0374f7de kevent64 + 10
1   libdispatch.dylib             	0x033d9593 _dispatch_mgr_invoke + 257
2   libdispatch.dylib             	0x033d92e3 _dispatch_mgr_thread + 60

Thread 2:
0   libsystem_kernel.dylib        	0x0374ed5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x0371334b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x03710f56 start_wqthread + 34

Thread 3:
0   libsystem_kernel.dylib        	0x0374ed5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x0371334b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x03710f56 start_wqthread + 34

Thread 4:: Dispatch queue: com.apple.root.default-qos.overcommit
0   libsystem_kernel.dylib        	0x0374ebb6 __sysctl + 10
1   libsystem_c.dylib             	0x0346a2be _os_assumes_log + 530
2   libxpc.dylib                  	0x036d782f _xpc_connection_init + 1069
3   libxpc.dylib                  	0x036d73f9 _xpc_connection_resume_init + 14
4   libdispatch.dylib             	0x033ea6ed _dispatch_client_callout + 14
5   libdispatch.dylib             	0x033d3850 _dispatch_root_queue_drain + 744
6   libdispatch.dylib             	0x033d3561 _dispatch_worker_thread3 + 108
7   libsystem_pthread.dylib       	0x0371325c _pthread_wqthread + 1050
8   libsystem_pthread.dylib       	0x03710f56 start_wqthread + 34

Thread 5 Crashed:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x0374e572 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x03716654 pthread_kill + 101
2   libsystem_c.dylib             	0x034b6729 __abort + 187
3   libsystem_c.dylib             	0x034b666e abort + 173
4   libc++abi.dylib               	0x032ddae7 abort_message + 151
5   libc++abi.dylib               	0x032fe683 default_terminate_handler() + 300
6   libobjc.A.dylib               	0x00b950b6 _objc_terminate() + 108
7   libc++abi.dylib               	0x032fbd0d std::__terminate(void (*)()) + 14
8   libc++abi.dylib               	0x032fb72b __cxa_throw + 122
9   libobjc.A.dylib               	0x00b94f23 objc_exception_throw + 339
10  com.apple.CoreFoundation      	0x008213bd +[NSException raise:format:] + 141
11  com.feedhenry.FHTests         	0x0c1ce7f0 -[LSNocilla responseForRequest:] + 880 (LSNocilla.m:79)
12  com.feedhenry.FHTests         	0x0c1cd528 -[LSHTTPStubURLProtocol startLoading] + 168 (LSHTTPStubURLProtocol.m:28)
13  com.apple.CFNetwork           	0x037c29b8 CFURLProtocol_NS::_protocolInterface_startLoad(_CFCachedURLResponse const*) + 324
14  com.apple.CFNetwork           	0x038c4fe4 ___ZN19URLConnectionLoader27_private_ScheduleOriginLoadEPK12NSURLRequestPK20_CFCachedURLResponse_block_invoke_2 + 62
15  com.apple.CFNetwork           	0x0379c428 ___ZNK19URLConnectionLoader25withExistingProtocolAsyncEU13block_pointerFvP11URLProtocolE_block_invoke + 30
16  libdispatch.dylib             	0x033ea6ed _dispatch_client_callout + 14
17  libdispatch.dylib             	0x033cf218 _dispatch_block_invoke + 377
18  libdispatch.dylib             	0x033e7f08 ___dispatch_block_create_block_invoke + 20
19  com.apple.CFNetwork           	0x0379c3fa RunloopBlockContext::_invoke_block(void const*, void*) + 24
20  com.apple.CoreFoundation      	0x007041f9 CFArrayApplyFunction + 57
21  com.apple.CFNetwork           	0x0379c2f5 RunloopBlockContext::perform() + 143
22  com.apple.CFNetwork           	0x0395c3da non-virtual thunk to RunloopBlockContext::multiplexerClientPerform() + 20
23  com.apple.CFNetwork           	0x0379c1b2 MultiplexerSource::perform() + 326
24  com.apple.CFNetwork           	0x0379bfca MultiplexerSource::_perform(void*) + 76
25  com.apple.CoreFoundation      	0x00733e5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
26  com.apple.CoreFoundation      	0x00729aeb __CFRunLoopDoSources0 + 523
27  com.apple.CoreFoundation      	0x00728f08 __CFRunLoopRun + 1032
28  com.apple.CoreFoundation      	0x00728846 CFRunLoopRunSpecific + 470
29  com.apple.CoreFoundation      	0x0072865b CFRunLoopRunInMode + 123
30  com.apple.CFNetwork           	0x03839036 +[NSURLConnection(Loader) _resourceLoadLoop:] + 472
31  com.apple.Foundation          	0x002c4eda -[NSThread main] + 76
32  com.apple.Foundation          	0x0037a2dc __NSThread__start__ + 1346
33  libsystem_pthread.dylib       	0x03713780 _pthread_body + 138
34  libsystem_pthread.dylib       	0x037136f6 _pthread_start + 155
35  libsystem_pthread.dylib       	0x03710f7a thread_start + 34

Thread 5 crashed with X86 Thread State (32-bit):
  eax: 0x00000000  ebx: 0x034e16dc  ecx: 0xb0216d6c  edx: 0x00000000
  edi: 0xb0219000  esi: 0x00000006  ebp: 0xb0216d88  esp: 0xb0216d6c
   ss: 0x00000023  efl: 0x00000206  eip: 0x0374e572   cs: 0x0000000b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000023   gs: 0x0000000f
  cr2: 0x0082c020

Logical CPU:     0
Error Code:      0x00080148
Trap Number:     132
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

** TEST FAILED: 56 passed, 0 failed, 1 errored, 57 total ** (29336 ms)
```

**Comment by corinnekrych** [comment]
@danielpassos @matzew I don't reproduce the issue when running the test locally but i think the issue is a nasty sync/async issue with Nocilla (https://github.com/luisobo/Nocilla/issues/136).
Since we got rid of ASIHTTP, I'd rather use OHHTTPStubs (for mocking http)

**Comment by matzew** [comment]
@corinnekrych now it's `testCloudHttpErrorResponse` that is failing 😢

**Comment by corinnekrych** [comment]
@matzew @danielpassos  The issue is Nocilla fwk, I've created https://issues.jboss.org/browse/FH-2784 I think for now with the Http tests commented we're good to merge. wdyt?

**Pull request merged**
