### PR TITLE
Fhmobsdk 57 update auth api

### PR DESCRIPTION
**Pull request by wei-lee**
There are mainly two changes in this PR:

1. New auth APIs for managing session tokens. 
Now the value of sessionToken returned in the FH.Auth requests will be persisted on device, and send to the cloud requests automatically. New APIs are added to check/remove/verify the sessionTokens.
2. Generate the starter project template for Github releases.
We still need the old starter project template as part of the Github releases. So added the templates back in and created a script to generate the files required by Github releases automatically.

Run the tests to verify.

### CODE REVIEW

**Comment by wei-lee** [comment]
@cvasilak mind to review?

**Comment by cvasilak** [comment]
:eyes: on  it

**Comment by cvasilak** [comment]
@wei-lee seems the ```FHDataManager.{h.m}``` files are not included in the PR, might to check?

**Comment by wei-lee** [comment]
@cvasilak The files are ignored, now they are added back in.

**Comment by cvasilak** [comment]
did the following:
 - created a policy on ag host and tested the implementation, worked as expected
 - regarding the github-release script, worked as expected too
 - further, all tests succeeded

opened a small PR https://github.com/feedhenry/fh-ios-sdk/pull/25 with some polish noticed in.

:+1: to merge afterwards

**Comment by wei-lee** [comment]
@cvasilak Thanks a lot.

**Pull request merged**
