### PR TITLE
Clean up 'gh-pages' and update README.md with installation instructions

### PR DESCRIPTION
**Pull request by cvasilak**
as described in the PR https://github.com/feedhenry/fh-ios-sdk/pull/20 the branch has been cleaned up to include only the documentation artifacts required by the GitHub pages feature and the README.md has been updated with installation insructions. 
> Eventually this branch will be eliminated as part of the  [FHMOBSDK-61](https://issues.jboss.org/browse/FHMOBSDK-61) work, and the API documentation will be moved to the FH documentation site.

***To test***:
Review README.md instructions and let me know if it's clear enough

@wei-lee @corinnekrych mind to review

### CODE REVIEW

**Comment by corinnekrych** [comment]
:eyes:

**Comment by corinnekrych** [comment]
@cvasilak since i'd like to test documentation generation without having a FH pods deplyoed, I tried to do it with an existing pod:
the command line:
> pod appledoc AeroGearHttp         
gives me this exception:  
appledoc version: 2.2.1 (build 1333)
Caught: AppledocException: At least one directory or file name path is required, use 'appledoc --help'
Docset has been generated for AeroGearHttp (0.2.0) and can be found in /Users/corinne/workspace/feedhenry/fh-ios-sdk/AeroGearHttp-0.2.0.

Do you know what i'm doing wrong?

**Comment by corinnekrych** [comment]
Last question: do you think we can specify which cocoapods repo we're targeting when generating doc? like we do for Podfile with ```source```?

**Comment by cvasilak** [comment]
have documented the pre-requisites in the main [README.md Release process] (https://github.com/cvasilak/fh-ios-sdk/tree/FHMOBSDK-19-cocoapods#release-process) not sure if it's worth duplicate this information here since it will be removed anyway as part of [FHMOBSDK-61](https://issues.jboss.org/browse/FHMOBSDK-61).

If you think we should do I am fine with it though.

**Comment by cvasilak** [comment]
appledoc fails cause it doesn't support Swift projects, something that is being looked in their [next version] (https://github.com/tomaz/appledoc/issues/460) though.

Technically, for Swift projects there is not ```spec.headers``` directive in Podspec to generate documentation since headers do not exist in Swift.

That said, hope there is going to be a [cocoapods-jazzy plugin] (https://github.com/tomaz/appledoc/issues/460)

**Comment by cvasilak** [comment]
> Last question: do you think we can specify which cocoapods repo we're targeting when generating doc? like we do for Podfile with source?

It doesn't provide an option to toggle private=public repo unfortunately but that said though from my tests  it doesn't affect since on the 'productization' phase only our private repo will exist and invoking the command will pick the one installed in-there, which is the correct behaviour.

eg. see an output of it when generating documentation for a testbed RHT build of AFNetworking

https://gist.github.com/cvasilak/5523cf9fea78172d9a30

This is for a private cocoapods FH repo created for tests:
https://github.com/cvasilak/feedhenry-repo/tree/master/Specs

@vibe13 for your info, let me know if there is any question/comment from your side too.

**Comment by corinnekrych** [comment]
Oki,
thanks @cvasilak 
+1

**Pull request merged**
