### PR TITLE
Add Meta Data to Datasets

### PR DESCRIPTION
**Pull request by evanshortiss**
Currently adding meta data to datasets isn't possible despite it being a property of the dataset class. It's not included with the HTTP requests either. This PR adds both, but is untested since I was unable to compile due to libPods.a not being available even after _pod install_. Lack of experience with pods on my part is the issue.

### CODE REVIEW

**Comment by evanshortiss** [comment]
@conoro, @johnfriz any plans to merge this for a future release?

**Comment by conoro** [comment]
@johnfriz Should we pass to Corinne for evaluation?

**Comment by corinnekrych** [comment]
:eyes: @evanshortiss did you open and build the *.xcworkspace file or the .xcodeproj?
After doing a pod install, open and work with generated workspace. Do you still face the issue?

**Comment by evanshortiss** [comment]
I believe this is the issue @corinnekrych. It was my first exposure to CocoaPods and I missed that, I since learned the error of my ways on another iOS endeavour! 

I'll check as soon as I can and verify tests are passing. I haven't added any new ones.

**Comment by evanshortiss** [comment]
@corinnekrych can confirm tests are passing

**Comment by wei-lee** [comment]
LGTM. Going to merge this.

**Comment by corinnekrych** [comment]
+1 to merge

**Comment by wei-lee** [comment]
Merged in 223d159ee92fb8b34d67caeef0d40a14157d38e7

**Comment by evanshortiss** [comment]
Thanks guys.

**Pull request closed without merging**
